language: python
sudo: true

python:
    - "3.7"
    - "3.8"

addons:
  apt:
    packages:
      - swig
      - softhsm2

before_install:
    - sudo chmod -R a+rx /etc/softhsm
    - sudo chown -R $(whoami) /var/lib/softhsm
    - mkdir /var/lib/softhsm/tokens

install:
    - pip install -r dev-requirements.txt
    - pip install .
    - softhsm2-util --init-token --slot 0 --label "A token" --pin 1234 --so-pin 123456

script:
    - make prepare4test
    - ./run_test.py
    - coverage run run_test.py

after_success:
    - coveralls
