name: GNU/Linux Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PYKCS11LIB: /usr/lib/softhsm/libsofthsm2.so

# A workflow run is made up of one or more jobs that can run
# sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on:  ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job
      # can access it
      - uses: actions/checkout@v3

      - name: setup prerequisites (linux)
        shell: bash
        run: sudo apt install swig softhsm2 python3-all-dev python3-setuptools

      - name: compile
        shell: bash
        run: make

      - name: test prep
        shell: bash
        run: |
          pip3 install -r dev-requirements.txt
          pip3 install .

      - name: test prep softhsm
        shell: bash
        run: |
          sudo chmod -R a+rx /etc/softhsm
          sudo chmod a+r /etc/softhsm/softhsm2.conf
          sudo chown -R $(whoami) /var/lib/softhsm
          softhsm2-util --init-token --slot 0 --label "A token" --pin 1234 --so-pin 123456

      - name: test run
        shell: bash
        run: |
          make tests

      - name: coverage
        shell: bash
        run: |
          coverage erase
          coverage run -m unittest discover
          coverage report

      - name: Covealls
        uses: AndreMiras/coveralls-python-action@develop
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

